### ISSUE TITLE
Looks nice but

### ISSUE THREAD

**Issue by AlexisTM** [cyrlop/pi-zero-ticker#1]
It looks nice but what happens once we reach 1M$ on GME?
Will the font size be reduced or will the screen even be able to show it?

**Comment by cyrlop** [comment]
I'll work on that when the price is around 95 000$
Just kidding, the font size needs to be adapted cood catch :)

**Comment by cyrlop** [comment]
Closed by 681322a067c8d8f7eccb26a5202655b5d47341c7
